from httpx import get

base_url = 'https://pdcaconsulting.com/wp-json/wp/v2'
page = 1

while True:
    api_url = f'{base_url}/posts?page={page}'
    r = get(api_url)
    
    # Check if the response is successful and has data
    if r.status_code != 200:
        break
    
    api_data = r.json()
    
    # Break if no more posts
    if not api_data:
        break
    
    # Process the posts
    for i in api_data:
        print(i.get('link'))
    
    page += 1
    
    # The code is generated by claude
    
    
    