from PIL import Image
file = ('Image Manupulation/picture.jpg')
img = Image.open(file)
#img.show()
black_write = img.convert('L')
#black_write.save('Image Manupulation/bw.jpg')
#black_write.show()
#print(list(black_write.getdata()))
mono = img.convert('1')
#mono.show()
#print(list(mono.getdata()))
#mono.save('Image Manupulation/mono.jpg')
RGBa = img.convert('RGBA')
#rgba.show()
RGBa.save('Image Manupulation/RGBa.jpg')